version: '3'
services:
  calendar_postgres:
    build: ./postgres
    container_name: calendar_postgres
    image: calendar_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
  calendar_api:
    build: ./app
    restart: always
    container_name: calendar_api
    image: calendar_api
    ports:
      - "80:80"
    environment:
      POSTGRES_HOST: calendar_postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: calendar_app 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    links:
      - calendar_postgres:calendar_postgres
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 10s
        timeout: 2s
        retries: 5
  calendar_front:
    build : ./calendar-frontend/
    container_name: calendar_front
    image: calendar_front
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_PORT: 80
      REACT_APP_API_HOST: http://localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 2s
      retries: 5



