name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: projetcalendar

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: projetcalendar.azurecr.io
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - name: Build and push container api
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: projetcalendar.azurecr.io/api
          file: ./app/dockerfile