name: Docker Compose Actions Workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file:"./docker-compose.yml"
          up-flags: "--build"
          services: |
            calendar_postgres
            calendar_api
            calendar_front
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network container:calendar-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:3000/
